chemist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('inventory/', include('inventory.urls')),
    path('', RedirectView.as_view(url='/inventory/', permanent=True)),# '' implies '/'
    path('admin/', admin.site.urls),
    path("accounts/", include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path 
from allauth.account.views import SignupView
from . import views

app_name = "inventory"

urlpatterns = [
    path("", SignupView.as_view(), name='index'),
    path("home/", views.index, name='home'),
    path("units/", views.UnitListView.as_view(), name='units'),
    path("unit-detail/<str:pk>/", views.UnitDetailView.as_view(), name='unit-detail'),
    path("unit/add/", views.UnitCreateView.as_view(), name='unit-add'),
    path("unit/<str:pk>/", views.UnitUpdateView.as_view(), name="unit-update"),
    path("vendors/", views.VendorListView.as_view(), name='vendors'),
    path('vendor-detail/<str:pk>/', views.VendorDetailView.as_view(), name='vendor-detail'),
    path("vendor/add/", views.VendorCreateView.as_view(), name="vendor-add"),
    path("vendor/<str:pk>/", views.VendorUpdateView.as_view(), name="vendor-update"),
    path('items/',views.ItemListView.as_view(), name='items'),
    path('item-detail/<str:pk>/', views.ItemDetailView.as_view(), name='item-detail'),
    path("item/add/", views.ItemCreateView.as_view(), name="item-add"),
    path("item/<str:pk>/", views.ItemUpdateView.as_view(), name="item-update"),
    path('purchaseorders/', views.PurchaseHeaderListView.as_view(), name='purchaseorders'),
    path('purchaseorder-detail/<str:pk>/', views.PurchaseHeaderDetailView.as_view(), name='purchaseorder-detail'),
    path("purchaseorder/add/", views.PurchaseOrderCreate.as_view(), name="purchaseorder-create"),
    path("purchase/<str:pk>/",views.PurchaseOrderReceive.as_view(), name="purchaseorder-receive"),
    path("purchase/<str:pk>/",views.PurchaseOrderUpdate.as_view(), name="purchaseorder-update"),
    path("cancelled-documents/", views.cancelled_documents, name='cancelled-documents'),
    path('purchasememos/', views.PurchaseCreditMemoListView.as_view(), name='purchasememos'),
    path('purchasememo-detail/<str:pk>', views.PurchaseCreditMemoDetailView.as_view(), name='purchasememo-detail'),
    path("purchasememos/add/", views.PurchaseCreditMemoCreate.as_view(), name='purchasememo-create'),
    path('invoices/', views.SalesInvoiceListView.as_view(), name='invoices'),
    path('invoice-detail/<str:pk>/', views.SalesInvoiceDetailView.as_view(), name='invoice-detail'),
    path("invoice/add/", views.SalesInvoiceCreate.as_view(), name='invoice-create'),
    path('get_batch_numbers/', views.get_batch_numbers, name='get_batch_numbers'),
    path("invoice/<str:pk>/",views.SalesInvoiceUpdate.as_view(), name="invoice-update"),
    path('salesmemos/', views.SalesCreditMemoListView.as_view(), name='salesmemos'),
    path('salesmemo-detail/<str:pk>', views.SalesCreditMemoDetailView.as_view(), name='salesmemo-detail'),
    path("salesmemo/add/", views.SalesCreditMemoCreate.as_view(), name="salesmemo-create"),
    path('approvals/', views.ApprovalListView.as_view(), name='approvals'),
    path('approval-detail/<int:pk>/', views.ApprovalDetailView.as_view(), name='approval-detail'),
    path('approval/<str:pk>/', views.ApprovalUpdateView.as_view(), name="approval-update"),
    path('profile/', views.UserProfile.as_view(), name='user-profile' ),
    path("approvalsetup/", views.ApprovalSetupListView.as_view(), name="approvalsetup"),
    path("approvalsetup-create/", views.ApprovalSetupCreateView.as_view(), name="approvalsetup-create"),
    path("approvalsetup-update/<str:pk>/", views.ApprovalSetupUpdateView.as_view(), name="approvalsetup-edit"),
    path("approvalsetup-detail/<str:pk>/", views.ApprovalSetupDetailView.as_view(), name="approvalsetup-detail"),
    path('invoice-printout/<str:pk>/', views.sales_pdf, name='invoiceprintout'),
    path('lpo-printout/<str:pk>/', views.purchases_pdf, name='lpoprintout'),
]

inventory/forms.py
from django import forms
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _
from . models import (Item, ItemEntry, Unit, Vendor, PurchaseHeader, PurchaseLine, PurchaseCreditMemoHeader, PurchaseCreditMemoLine, SalesHeader, 
                      SalesLine, SalesCreditMemoHeader, SalesCreditMemoLine, ApprovalEntry)


class SalesHeaderForm(forms.ModelForm):
    class Meta:
        model = SalesHeader
        fields = ['customer']

class SalesLinesForm(forms.ModelForm):
    class Meta:
        model = SalesLine
        fields = ['item', 'lpo', 'quantity', 'discount']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['lpo'].widget = forms.Select(attrs={'class': 'item-entry-select'})

        self.fields['lpo'].queryset = ItemEntry.objects.none()

        self.fields['lpo'].widget.attrs['onchange'] = 'updateBatchNumbers()'

SalesLinesFormset = forms.inlineformset_factory(SalesHeader, SalesLine, form=SalesLinesForm, can_delete=True, can_delete_extra=True, extra=1)

class SalesLinesUpdateForm(forms.ModelForm):
    class Meta:
        model = SalesLine 
        fields = ['item', 'lpo', 'quantity', 'discount']

SalesLineUpdateFormset = forms.inlineformset_factory(SalesHeader, SalesLine, form=SalesLinesUpdateForm, can_delete=False, extra=0)

class PurchaseHeaderForm(forms.ModelForm):
    class Meta:
        model = PurchaseHeader
        fields = ['vendor']

class PurchaseLineForm(forms.ModelForm):
    class Meta:
        model = PurchaseLine
        fields = ['item', 'quantity_requested', 'unit_price']

PurchaseLineFormset = forms.inlineformset_factory(PurchaseHeader, PurchaseLine, form=PurchaseLineForm, can_delete=True, can_delete_extra=True, extra=1)

class PurchaseLineReceivingForm(forms.ModelForm):
    class Meta:
        model = PurchaseLine
        fields = ['quantity_received', 'batch', 'expiry_date', 'markup', 'invoice_no']

PurchaseLineReceivingFormset = forms.inlineformset_factory(PurchaseHeader, PurchaseLine, form=PurchaseLineReceivingForm, can_delete=False,extra=0)

class SalesCreditMemoHeaderForm(forms.ModelForm):
    class Meta:
        model = SalesCreditMemoHeader
        fields = ['invoice_no']

class SalesCreditMemoLineForm(forms.ModelForm):
    class Meta:
        model = SalesCreditMemoLine
        fields = ['sales_line', 'quantity']

SalesCreditMemoLineFormset = forms.inlineformset_factory(SalesCreditMemoHeader, SalesCreditMemoLine, form=SalesCreditMemoLineForm, extra=1)

class PurchaseCreditMemoHeaderForm(forms.ModelForm):
    class Meta:
        model = PurchaseCreditMemoHeader
        fields = ['vendor']

class PurchaseCreditMemoLineForm(forms.ModelForm):
    class Meta:
        model = PurchaseCreditMemoLine
        fields = ['purchase_line','quantity']

PurchaseCreditMemoLineFormset = forms.inlineformset_factory(PurchaseCreditMemoHeader, PurchaseCreditMemoLine, form=PurchaseCreditMemoLineForm, extra=1)

class ApprovalEntryForm(forms.ModelForm):
    class Meta:
        model = ApprovalEntry
        fields = '__all__'
        widgets = {
            'reason': forms.Textarea(attrs={'rows': 3}),  # You can choose an appropriate widget
        }

inventory/views.py
from django.db import models
from django.forms.models import BaseModelForm
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.http import HttpResponse, Http404, JsonResponse, FileResponse, StreamingHttpResponse, HttpResponseBadRequest
from django.contrib import messages
from .models import (Item, ItemEntry, PurchaseHeader, PurchaseLine, SalesHeader, SalesLine, Vendor, Unit, ApprovalEntry, SalesCreditMemoHeader, 
                     SalesCreditMemoLine, PurchaseCreditMemoHeader, PurchaseCreditMemoLine, Profile, ApprovalSetup)
from django.views import generic, View
from django.template import loader
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django import forms
from . forms import (SalesHeaderForm, PurchaseHeaderForm, SalesLinesFormset, PurchaseLineFormset,SalesCreditMemoHeaderForm, SalesCreditMemoLineFormset,
                     PurchaseCreditMemoHeaderForm, PurchaseCreditMemoLineFormset, PurchaseLineReceivingFormset, SalesLineUpdateFormset, ApprovalEntryForm)
from django.contrib.auth.decorators import login_required
from django.core.files.base import ContentFile
from django.templatetags.static import static
from django.contrib.staticfiles import finders
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Image, Spacer, PageTemplate
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus.frames import Frame
from django.db.models import Sum
import csv
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.http import require_POST
from django_filters.views import FilterView
from . filters import ItemFilter


@login_required
def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_items = Item.objects.count()
    num_vendors = Vendor.objects.count()
    num_invoices = SalesHeader.objects.count()
    num_lpos = PurchaseHeader.objects.count()
    pending_lpo = PurchaseHeader.objects.filter(status=1).count()
    open_lpo = PurchaseHeader.objects.filter(status=0).count()
    total_sales = SalesHeader.objects.aggregate(total=Sum('amount'))['total']
    open_lpo_value = PurchaseHeader.objects.filter(status=0).aggregate(total=Sum('total'))['total']
    released_lpos = PurchaseHeader.objects.filter(status=2).aggregate(total=Sum('total'))['total']
    pending_lpo_value = PurchaseHeader.objects.filter(status=1).aggregate(total=Sum('total'))['total']
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_items': num_items,
        'num_vendors': num_vendors,
        'num_invoices': num_invoices,
        'num_lpos': num_lpos,
        'num_visits': num_visits,
        'pending_lpo': pending_lpo,
        'open_lpo': open_lpo,
        'total_sales': total_sales,
        'open_lpo_value': open_lpo_value,
        'released_lpos': released_lpos,
        'pending_lpo_value': pending_lpo_value
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'inventory/index.html', context=context)
@login_required
def cancelled_documents(request):
    lpos = PurchaseHeader.objects.filter(status=3)
    context = {
        'lpos': lpos
    }
    return render(request, 'inventory/cancelled.html', context=context)
class VendorListView(LoginRequiredMixin, generic.ListView):
    model = Vendor
    paginate_by = 25

class VendorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Vendor
    paginate_by = 25

class VendorCreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Vendor
    fields = ['description', 'contact_email', 'contact_phone', 'address', 'kra_pin']
    success_url = reverse_lazy("vendors")
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class VendorUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Vendor
    fields = ['contact_email', 'contact_phone', 'address']

class ItemListView(LoginRequiredMixin, generic.ListView, FilterView):
    model = Item
    paginate_by = 25
    filterset_class = ItemFilter
    template_name = 'inventory/item_list.html'

class ItemDetailView(LoginRequiredMixin, generic.DetailView):
    model = Item
    paginate_by = 25

class ItemCreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Item
    fields = ['code','description', 'unit']
    success_url = reverse_lazy("items")
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class ItemUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Item
    fields = ['unit']

class PurchaseHeaderListView(LoginRequiredMixin, generic.ListView):
    model = PurchaseHeader
    paginate_by = 25

class PurchaseHeaderDetailView(LoginRequiredMixin, generic.DetailView):
    model = PurchaseHeader
    template_name = 'inventory/purchaseheader_detail.html'

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(PurchaseHeader, number=pk)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['messages'] = messages.get_messages(self.request)
        return context

    def post(self, request, pk):
        if request.method == 'POST':
            purchase_header = self.get_object()
            amount = purchase_header.total
            
            approval_entries = ApprovalEntry.objects.filter(document_number=purchase_header).order_by('-request_date')
            if approval_entries and approval_entries[0].status==1:
                approval_entry = approval_entries[0]
                approval_entry.status = 0
                approval_entry.save()
                messages.success(request, 'Approval request cancelled')
                return redirect('inventory:purchaseorder-detail', pk=pk)
            else:
                if pk and amount:
                    try:
                        approver_setup = ApprovalSetup.objects.get(user=request.user)
                        approver = approver_setup.approver
                    except ApprovalSetup.DoesNotExist:
                        approver = None 
                    
                    ApprovalEntry.objects.create(
                        requester=request.user,
                        document_number=purchase_header,
                        details="Your details here",
                        amount=amount, 
                        approver=approver,
                        request_date=timezone.now()
                    )
                    messages.success(request, 'Approval request sent')
                    return redirect('inventory:purchaseorder-detail', pk=pk)
                    # return JsonResponse({'message': 'Approval request sent'})
                else:
                    messages.error(request, 'Missing document_number or amount')
                    return redirect('inventory:purchaseorder-detail', pk=pk)
                    #return JsonResponse({'error': 'Missing document_number or amount'}, status=400)
        else:
            messages.error(request, 'Invalid request method')
            return redirect('inventory:purchaseorder-detail', pk=pk)
            #return JsonResponse({'error': 'Invalid request method'}, status=400)

# This is for DRY; the class is used for creation and updating
class PurchaseHeaderInline():
    form_class = PurchaseHeaderForm
    model = PurchaseHeader
    template_name = "inventory/purchase_order_create_or_update.html"

    def form_valid(self, form):
        named_formsets = self.get_named_formsets()
        if not all((x.is_valid() for x in named_formsets.values())):
            return self.render_to_response(self.get_context_data(form=form))
        self.object = form.save()
        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, 'formset_{0}_valid'.format(name), None)
            if formset_save_func is not None:
                formset_save_func(formset) # executes formset_purchaselines_valid function below
            else:
                formset.save()
        url = reverse_lazy('inventory:purchaseorder-detail', kwargs={'pk': str(self.object.pk)})
        return redirect(url)
    # custom save function for purchaselines formset
    def formset_purchaselines_valid(self, formset):
        purchaselines = formset.save(commit=False) 
        for obj in formset.deleted_objects:
            obj.delete()
        for purchaseline in purchaselines:
            purchaseline.number = self.object
            purchaseline.save()

class PurchaseOrderCreate(LoginRequiredMixin, PurchaseHeaderInline, generic.edit.CreateView):
    def get_context_data(self, **kwargs):
        context = super(PurchaseOrderCreate, self).get_context_data(**kwargs)
        context['named_formsets'] = self.get_named_formsets()
        return context
    
    def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'purchaselines': PurchaseLineFormset(prefix='lines'),
            }
        else:
            return {
                'purchaselines': PurchaseLineFormset(self.request.POST or None, prefix='lines'),
            }

class PurchaseOrderUpdate(LoginRequiredMixin, PurchaseHeaderInline, generic.edit.UpdateView):
    def get_context_data(self, **kwargs):
        context = super(PurchaseOrderUpdate, self).get_context_data(**kwargs)
        context['named_formsets'] = self.get_named_formsets()
        return context
    
    def get_named_formsets(self):
            return {

inventory/templates/inventory/approvalentry_detail.html
{% extends "inventory/base.html" %}
{% block title %}
 Approval Details
{% endblock %}
{% block content %}
<a href="{% url 'inventory:approvals'%}"><button>Back</button></a>
{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
<h2>Approval Entry Card</h2>
{% if approvalentry.status == '1'%}
<form id="approval-form" method="post">
    {% csrf_token %}
    <!-- Your other form elements here -->
    <!-- {{ form.as_p }}  -->
    <button id="approve-approval-request">Approve</button>
    <button id="reject-approval-request">Reject</button>
</form>
{% endif %}
<ul>
    <li>Requester: {{ approvalentry.requester }}</li>
    <li>Document Number: {{ approvalentry.document_number }}</li>
    <li>Details: {{ approvalentry.details}}</li>
    <li>Amount: {{ approvalentry.amount}}</li>
    <li>Due Date: {{approvalentry.due_date}}</li>
    <li>Over Due: {{approvalentry.overdue}}</li>
    {% if approvalentry.status == '2' or approvalentry.status == '3' %}
    <li>Status: {{ approvalentry.status }}</li>
    {% endif %}
</ul>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(document).ready(function() {
        $("#approve-approval-request").click(function() {
            handleApproval('approve');
        });

        $("#reject-approval-request").click(function() {
            handleApproval('reject');
        });

        function handleApproval(action) {
            var documentNumber = "{{ approvalentry.id }}";
            var csrfToken = $("input[name='csrfmiddlewaretoken']").val();
            console.log(action);

            $.ajax({
                url: "{% url 'inventory:approval-detail' approvalentry.id %}",
                method: "POST",
                data: {
                    document_number: documentNumber,
                    action: action,
                    csrfmiddlewaretoken: csrfToken
                }
            });
        }
    });
</script>
{% endblock %}

inventory/templates/inventory/approvalentry_form.html
{% extends "inventory/base.html" %}
{% block title %}
 Approve LPO
{% endblock %}
{% block content %}
    <h1>Approval Entry</h1>
    <form action="" method="post">{% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Save">
    </form>
{% endblock %}

inventory/templates/inventory/cancelled.html
{% extends "inventory/base.html" %}
    {% block title %}Cancelled Documents{% endblock title %}
{% block content %}
<h1>List Cancelled of documents</h1>
<ul>
    {% for lpo in lpos %}
    <li><a href="{% url 'inventory:purchaseorder-detail' lpo.number %}">{{lpo.number}}</a>&#124; {{lpo.vendor}}&#124; Ksh.{{lpo.total}}&#124; {{lpo.status}}
    {% endfor %}
</ul>
{% endblock content %}

inventory/templates/inventory/item_details.html
{% extends "base.html" %}
{% block title %}
    Item Details
{% endblock %}
{% block content %}
    <h1>Details</h1>
{% endblock %}

inventory/templates/inventory/purchasecreditmemoheader_list.html
{% extends "inventory/base.html" %}
{% block title %}
    Purchase Credit Memos
{% endblock %}
{% block content %}
    <h1>List of Purchase Credit Memos</h1>
    <a href="{% url 'inventory:purchasememo-create' %}">Create Purchase Credit Memo</a>
    <ul>
        {% for purchasememo in purchasecreditmemoheader_list %}
        <li><a href="{% url 'inventory:purchasememo-detail' purchasememo.number %}">{{purchasememo.number}}</a></li>
        {% endfor %}
    </ul>
        
{% endblock %}

inventory/templates/inventory/sales_invoice_create_or_update.html
{% extends "inventory/base.html" %}

{% block content %}
<form enctype="multipart/form-data" class="container" method="post" id="product_form">
    {% csrf_token %}
    <div class="card">
        <div class="card-header card-header-secondary">
            <h4 class="card-title">Sales Header</h4>
        </div>
        {% for field in form %}
            <div class="form-group card-body">
                <label>{{field.label}}</label>
                {% if field.field.required %}
                    <span style="color: red;" class="required">*</span>
                {% endif %}
            
                {{field}}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}
    </div>

    {% with named_formsets.saleslines as formset %}
        {{ formset.management_form }}
        <script type="text/html" id="saleslines-template">   <!--id="inlineformsetname-template"-->
            <!--id='inlineformsetname-__prefix__' -->
            <tr id="saleslines-__prefix__" class= hide_all>
                {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                {% endfor %}
            
                {% for fields in formset.empty_form.visible_fields %}
                    <td>{{fields}}</td>
                {% endfor %}
            </tr>
        </script>
        <div class="table-responsive card mt-4">
            <div class="card-header card-header-secondary">
                <h4 class="card-title">Sales Lines</h4>
            </div>
            <table class="table card-header">
                <thead class="text-secondary">
                    <th>Item <span id='id_item' style="color: red;" class="required">*</span></th>
                    <th>Item entry <span id='id_lpo' style="color: red;" class="required">*</span></th>
                    <th>Quantity <span style="color: red;" class="required">*</span></th>
                    <th>Discount <span style="color: red;" class="required">*</span></th>
                    <th>Delete?</th>
                </thead>
                <tbody id="item-saleslines"> 
                    {% for error in formset.non_form_errors %}
                        <span style="color: red">{{ error }}</span>
                    {% endfor %}
                    {% for formss in formset %}
                        {{ formss.management_form }}
                        <tr id="saleslines-{{ forloop.counter0 }}" class= hide_all> 
                            {{ formss.id }}
                            {% for field in formss.visible_fields %}
                                <td>
                                    {{field}}
                                    {% for error in field.errors %}
                                        <span style="color: red">{{ error }}</span>
                                    {% endfor %}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <button id="add-saleslines-button" class="btn btn-secondary add-saleslines">Add More</button>
        </div>
        
        {% endwith %}

        <div class="form-group">
            <button type="submit" class="btn btn-secondary btn-block">Submit</button>
        </div>
</form>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
  $(document).ready(function() {
      $('.add-saleslines').click(function(ev) {
          ev.preventDefault();
          var count = $('#item-saleslines').children().length;
          var tmplMarkup = $('#saleslines-template').html();
          var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
          $('#item-saleslines').append(compiledTmpl);
  
          // update form count
          $('#id_lines-TOTAL_FORMS').attr('value', count+1);
      });
  });
  function updateBatchNumbers() {
        // Get the selected item's ID
        var itemId = $('#id_item').val();
        
        // Make an AJAX request to fetch batch numbers for the selected item
        $.ajax({
            url: "{% url 'inventory:get_batch_numbers' %}", 
            data: {'item_id': itemId},
            success: function(data) {
                // Update the batch numbers options in the form
                var options = '<option value="">---------</option>';
                for (var i = 0; i < data.batch_numbers.length; i++) {
                    options += '<option value="' + data.batch_numbers[i].id + '">' + data.batch_numbers[i].name + '</option>';
                }
                $('#id_lpo').html(options);
            }
        });
    }
</script>
        
{% endblock content %}

inventory/templates/inventory/salescreditmemoheader_list.html
{% extends "inventory/base.html" %}
{% block title %}
    Sales Credit Memos
{% endblock %}
{% block content %}
    <h1>List of Sales Credit Memos</h1>
    <a href="{% url 'inventory:salesmemo-create' %}">Create Sales Credit Memo</a>
    <ul>
        {% for salesmemo in salescreditmemoheader_list %}
        <li><a href="{% url 'inventory:salesmemo-detail' salesmemo.number %}">{{salesmemo.number}}</a></li>
        {% endfor %}
    </ul>
        
{% endblock %}

inventory/templates/inventory/salesheader_list.html
{% extends "inventory/base.html" %}
{% block title %}
    Sales Invoices
{% endblock %}
{% block content %}
    <h1>List of Sales invoices</h1>
    <a href="{% url 'inventory:invoice-create' %}">Create Sales invoice</a>
    <ul>
        {% for invoice in salesheader_list %}
        <li><a href="{% url 'inventory:invoice-detail' invoice.number %}">{{invoice.number}}</a>&#124; {{invoice.customer}}&#124; Ksh.{{invoice.amount}}</li>
        {% endfor %}
    </ul>
        
{% endblock %}

inventory/templates/inventory/unit_detail.html
{% extends "inventory/base.html" %}
{% block title %}
    Unit of Measure
{% endblock %}
{% block content %}
    <h1>Unit Card</h1>
    <a href="{% url 'inventory:unit-update' unit.code %}">Update</a>
    <ul>
        <li><strong>Code:</strong>{{unit.code}}</li>
        <li><strong>Name:</strong>{{unit.description}}</li>
    </ul>
{% endblock %}